<footer role="contentinfo" class="uma-footer">
  <div class="footer-inner">
    <div class="footer-nav footer-nav-flat">
      <ul>
        <li><a href="page/imprint">Impressum</a></li>
        <li><a href="https://www.uni-mannheim.de/datenschutzerklaerung/">Datenschutzerklärung</a></li>
      </ul>
    </div>
    <div class="logos">
      <div class="logo1">
        <a href="https://www.uni-mannheim.de">
          <img class="uni-logo" src="<?= $this->assetUrl(('img/logos/UM_Logo_DE_k.svg')); ?>" alt="Logo Uni Mannheim" title="Logo Uni Mannheim" />
        </a>
      </div>
      <div class="logo2">
        <span class="hosted">Hosted by<br /></span>
        <a href="https://www.bib.uni-mannheim.de">
          <img class="ub-logo" src="<?= $this->assetUrl(('img/logos/UB_d_w.svg')); ?>" alt="Logo UB Mannheim" title="Logo UB Mannheim" />
        </a>
      </div>
    </div>
  </div>
</footer>